name: prabhatpipeline
trigger:
 branches:
     include:
         - main
pool:
  name: prabhatpool1
variables:
  ps12: "pranamservice_123"
stages:
    - stage: buildstage
      displayName: build stage
      jobs:
          - job: buildjob
            displayName: build job
            steps:
            - task: TerraformInstaller@1
              inputs:
                terraformVersion: 'latest'
          
